# This stack is based on `config/prod/dgutman-htan-new2-ec2.yaml`
# in https://github.com/Sage-Bionetworks/sandbox-provisioner/
template_path: "managed-ec2-linux-htan.j2"
stack_name: "dgutman-dsa-server-preprod-ec2"

sceptre_user_data:
  Distro: "ubuntu"
  OpenPorts: ["80", "443", "22"]
parameters:
  Department: "CompOnc"
  Project: "htan"
  OwnerEmail: "bruno.grande@sagebase.org"
  InstanceType: "i3en.2xlarge"
  AMIId: "ami-0b7906ab614596e7e"  # https://github.com/Sage-Bionetworks-IT/packer-base-ubuntu-bionic/releases/tag/v1.0.9
  VolumeSize: "1000"
  KeyName: "EmoryHealthcare-dgutman"  # Imported via AWS Management Console
  VpcName: "htan-vpc"
  VpcSubnet: "PublicSubnet"
