template:
  type: "http"
  url: "{{stack_group_config.aws_infra_templates_root_url}}/v0.2.13/templates/VPC/vpc-mini.yaml"
stack_name: htan-vpc
stack_tags:
  Department: "CompOnc"
  Project: "htan"
  OwnerEmail: "bruno.grande@sagebase.org"
  CostCenter: "HTAN-DFCI / 120100"
parameters:
  VpcName: htan-vpc
  VpcSubnetPrefix: "10.255.31"
